version: "3.5"
services:
  app:
    image: golang:latest
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src/app
    ports:
      - 8080:8080
    working_dir: /go/src/app